# Generated by Django 4.2.14 on 2024-07-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('PlanoAula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='mensagemplanoaula',
            name='mensagem_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='PlanoAula.mensagemplanoaula', verbose_name='Mensagem original'),
        ),
        migrations.AddField(
            model_name='mensagemplanoaula',
            name='plano_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mensagens', to='PlanoAula.planoaula', verbose_name='Plano de aula'),
        ),
        migrations.AddField(
            model_name='mensagemplanoaula',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='likeplanoaula',
            name='plano_aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='likes', to='PlanoAula.planoaula', verbose_name='Plano de aula'),
        ),
        migrations.AddField(
            model_name='likeplanoaula',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='fotorobo',
            name='plano_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fotos_robo', to='PlanoAula.planoaula', verbose_name='Plano de aula'),
        ),
        migrations.AddField(
            model_name='fotoexecucao',
            name='plano_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fotos_execucao', to='PlanoAula.planoaula', verbose_name='Plano de aula'),
        ),
        migrations.AddField(
            model_name='execucaoplanoaula',
            name='plano_aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='execucoes', to='PlanoAula.planoaula', verbose_name='Plano de aula'),
        ),
        migrations.AddField(
            model_name='execucaoplanoaula',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário'),
        ),
    ]
