# Generated by Django 4.2.14 on 2025-06-22 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_usuario_estado'),
        ('PlanoAula', '0005_alter_planoaula_nivel_dificuldade_montagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaoplanoaula',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='execucoes_plano_aula', to='Usuario.usuario', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='likeplanoaula',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='likes_plano_aula', to='Usuario.usuario', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='planos_criados', to='Usuario.usuario', verbose_name='Responsável'),
        ),
    ]
