# Generated by Django 4.2.14 on 2024-07-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestaodisciplina',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='sugestaoconteudo',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Disciplina.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='sugestaoconteudo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conteudos', to='Disciplina.disciplina', verbose_name='Disciplina'),
        ),
    ]
