# Generated by Django 4.2.14 on 2025-06-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplina', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome'),
        ),
        migrations.AddConstraint(
            model_name='conteudo',
            constraint=models.UniqueConstraint(fields=('nome', 'disciplina'), name='unique_conteudo_por_disciplina'),
        ),
    ]
