# Generated by Django 4.2.14 on 2025-01-27 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Artigo', 'Artigo'), ('Tese', 'Tese'), ('Dissertação', 'Dissertação'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Kit', 'Kit'), ('Outro', 'Outro')], default='Outro', help_text='Selecione o tipo de material do acervo.', max_length=20)),
                ('titulo', models.CharField(help_text='Título ou nome do item do acervo.', max_length=255)),
                ('descricao', models.TextField(help_text='Breve descrição do conteúdo ou características do item.')),
                ('autor', models.CharField(help_text='Autor ou criador principal do item.', max_length=255)),
                ('ano', models.PositiveIntegerField(default=2024, help_text='Ano de publicação/criação do item.')),
                ('link', models.URLField(blank=True, help_text='Link para acesso online (opcional).', null=True)),
                ('file', models.FileField(blank=True, help_text='Arquivo local associado ao item, se houver.', null=True, upload_to='acervo_files/')),
                ('licenca_de_uso', models.CharField(default='Sem Licença', help_text='Tipo de licença ou permissão de uso.', max_length=255)),
                ('data_adicao', models.DateField(auto_now_add=True, help_text='Data de adição do item no sistema.')),
                ('responsavel', models.ForeignKey(help_text='Usuário responsável por submeter este item ao acervo.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
