# Generated by Django 4.2.14 on 2024-07-25 13:48

import Acoes.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('Evento', 'Evento'), ('Curso', 'Curso'), ('Palestra', 'Palestra'), ('Outro', 'Outro')], default='Evento', max_length=8)),
                ('data_inicio', models.DateField(default=datetime.date.today, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Está em execução')),
                ('deletada', models.BooleanField(default=False, verbose_name='Deletado')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['-status', '-data_inicio', '-data_fim', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midia', models.ImageField(blank=True, null=True, upload_to=Acoes.models.user_directory_path)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='midias', to='Acoes.acoes', verbose_name='Ação')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['acao', 'data'],
            },
        ),
        migrations.CreateModel(
            name='MensagemAcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acoes.acoes', verbose_name='Ação')),
                ('mensagem_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Acoes.mensagemacoes', verbose_name='Mensagem original')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['acao', 'mensagem_original__pk', '-data'],
            },
        ),
    ]
