# Generated by Django 4.2.14 on 2024-07-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Acoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemacoes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='acoes',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Responsável'),
        ),
    ]
