# Generated by Django 4.2.14 on 2024-07-25 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Acoes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemacoes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário'),
        ),
    ]
