# Generated by Django 4.2.14 on 2024-08-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0003_alter_mensagemacoes_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='formato',
            field=models.CharField(choices=[('Híbrido', 'Híbrido'), ('Presencial', 'Presencial'), ('Online', 'Online')], default='Híbrido', max_length=10),
        ),
        migrations.AddField(
            model_name='acoes',
            name='link_do_evento',
            field=models.URLField(blank=True, null=True, verbose_name='Link do evento'),
        ),
        migrations.AddField(
            model_name='acoes',
            name='site_do_evento',
            field=models.URLField(blank=True, null=True, verbose_name='Site do evento'),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='tipo',
            field=models.CharField(choices=[('Competição', 'Competição'), ('Curso', 'Curso'), ('Evento', 'Evento'), ('Palestra', 'Palestra'), ('Outro', 'Outro')], default='Competição', max_length=10),
        ),
    ]
