# Generated by Django 4.2.14 on 2024-08-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0005_rename_link_do_evento_acoes_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acoes',
            name='link',
        ),
        migrations.AddField(
            model_name='acoes',
            name='link_de_acesso',
            field=models.URLField(blank=True, null=True, verbose_name='Link de acesso'),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
    ]
