# Generated by Django 4.2.14 on 2025-06-22 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_usuario_estado'),
        ('Acoes', '0006_remove_acoes_link_acoes_link_de_acesso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='acoes_cadastradas', to='Usuario.usuario', verbose_name='Responsável'),
        ),
    ]
