# Generated by Django 4.2.14 on 2026-04-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0007_alter_acoes_responsavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acoes',
            options={'ordering': ['-data_inicio', '-data_fim', 'titulo'], 'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
    ]
