# Generated by Django 5.2.4 on 2025-12-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0007_alter_acoes_responsavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acoes',
            options={'ordering': ['-data_inicio', '-data_fim', 'titulo'], 'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
    ]
