# Generated by Django 5.2.4 on 2026-06-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Administrador', 'Administrador')], default='Aluno', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
