# Generated by Django 5.2.4 on 2026-06-24 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Administrador', 'Administrador'), ('Root', 'Root')], default='Aluno', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.CreateModel(
            name='CodigoValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('tipo', models.CharField(choices=[('CADASTRO', 'Confirmação de Cadastro'), ('ADMIN', 'Ação Administrativa')], max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('utilizado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_validacao', to='Usuario.usuario')),
            ],
        ),
    ]
