# Generated by Django 5.2.4 on 2026-06-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_alter_usuario_tipo_usuario_codigovalidacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigovalidacao',
            name='tipo',
            field=models.CharField(choices=[('CADASTRO', 'Confirmação de Cadastro'), ('ADMIN', 'Ação Administrativa'), ('RECUPERACAO', 'Recuperação de Senha')], max_length=11),
        ),
    ]
