# Generated by Django 4.2.14 on 2024-07-25 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mensagemplanoaula',
            name='plano_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='PlanoAula.planoaula', verbose_name='Plano de aula'),
        ),
    ]
