# Generated by Django 4.2.14 on 2024-08-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0003_planoaula_status_alter_mensagemplanoaula_plano_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='nivel_dificuldade_montagem',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Intermediário', 'Intermediário'), ('Difícil', 'Difícil')], default='Fácil', max_length=13, verbose_name='Nível de dificuldade na montagem'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='nivel_dificuldade_programacao',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Intermediário', 'Intermediário'), ('Difícil', 'Difícil')], default='Fácil', max_length=13, verbose_name='Nível de dificuldade na programação'),
        ),
    ]
