# Generated by Django 4.2.14 on 2024-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0004_planoaula_nivel_dificuldade_montagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoaula',
            name='nivel_dificuldade_montagem',
            field=models.CharField(blank=True, choices=[('Fácil', 'Fácil'), ('Intermediário', 'Intermediário'), ('Difícil', 'Difícil')], max_length=13, null=True, verbose_name='Nível de dificuldade da montagem'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='nivel_dificuldade_programacao',
            field=models.CharField(blank=True, choices=[('Fácil', 'Fácil'), ('Intermediário', 'Intermediário'), ('Difícil', 'Difícil')], max_length=13, null=True, verbose_name='Nível de dificuldade da programação'),
        ),
    ]
