# Generated by Django 4.2.14 on 2024-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PlanoAula', '0001_initial'),
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aulas',
            field=models.ManyToManyField(related_name='aulas', through='Curso.Aulas', to='PlanoAula.planoaula', verbose_name='Aulas'),
        ),
    ]
