# Generated by Django 4.2.14 on 2024-07-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('PlanoAula', '0001_initial'),
        ('Curso', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='aulas',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cursos', to='PlanoAula.planoaula', verbose_name='Plano de aula'),
        ),
        migrations.AddField(
            model_name='aulas',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cursos', to='Curso.curso', verbose_name='Curso'),
        ),
    ]
