# Generated by Django 4.2.14 on 2024-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=7)),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['disciplina', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=7)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SugestaoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('status', models.CharField(choices=[('A', 'Em espera'), ('B', 'Aprovado'), ('C', 'Negado')], default='A', max_length=1)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentários')),
                ('data', models.DateField(auto_now_add=True, null=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Sugestão de Conteúdo',
                'verbose_name_plural': 'Sugestões de Conteúdo',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='SugestaoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('status', models.CharField(choices=[('A', 'Em espera'), ('B', 'Aprovado'), ('C', 'Negado')], default='A', max_length=1)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentários')),
                ('data', models.DateField(auto_now_add=True, null=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Sugestão de Disciplina',
                'verbose_name_plural': 'Sugestões de Disciplina',
                'ordering': ['status'],
            },
        ),
    ]
