# Generated by Django 4.2.14 on 2024-08-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0004_acoes_formato_acoes_link_do_evento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acoes',
            old_name='link_do_evento',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='acoes',
            old_name='site_do_evento',
            new_name='site',
        ),
    ]
